services:
  - type: web
    name: nexus-music-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node main.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false 